controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

use app\models\LoginForm;
use app\models\SignupForm;
use app\models\User;
use app\models\CashAccount;

class AuthController extends Controller
{

	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			$ca = CashAccount::findOne(['user_id' => Yii::$app->user->id]);
			if($ca == null){
				$ca = new CashAccount();
				$ca->user_id = Yii::$app->user->id; 
				$ca->points = 0;
				$ca->points = 0;
				$ca->save();
			}
			return $this->goBack();
		}
		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout()
	{
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function actionSignup()
	{
		$model = new SignupForm();

		if(Yii::$app->request->isPost)
		{
			$model->load(Yii::$app->request->post());
			if($model->signup())
			{
				return $this->redirect(['auth/login']);
			}
		}

		return $this->render('signup', ['model'=>$model]);
	}
}

views/layouts/account.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use app\models\User;
use app\assets\UserAsset;

UserAsset::register($this);
$user = User::findOne(Yii::$app->user->id);
$admin = $user->is_admin == 1;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body class=" theme-blue">

	<?php $this->beginBody() ?>
	<?= $this->render('/partials/navbar-ac', ['user' => $user]);?>

	<?php if ($admin): ?>
		<?= $this->render('/partials/sidebar-ac');?>
	<?php endif ?>

	<div class="content" <?= !$admin ? 'style="margin-left:0"': '' ?>>
		<?= $content ?>
	</div>

	<?php $this->endBody() ?>
<?php $this->registerJsFile('/ckeditor/ckeditor.js');?>
<?php $this->registerJsFile('/ckfinder/ckfinder.js');?>
<script>
	$(document).ready(function(){
		var editor = CKEDITOR.replaceAll();
		CKFinder.setupCKEditor( editor );
	})
</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Модуль управления заказами',
        'brandUrl' => ['/admin/default/index'],
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Товары', 'url' => ['/admin/product/index']],
            ['label' => 'Кактегории', 'url' => ['/admin/category/index']],
            ['label' => 'Заказы', 'url' => ['/admin/order/index']],
            ['label' => 'Выход', 'url' => ['/auth/logout']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
<?php $this->registerJsFile('/ckeditor/ckeditor.js');?>
<?php $this->registerJsFile('/ckfinder/ckfinder.js');?>
<script>
    $(document).ready(function(){
        var editor = CKEDITOR.replaceAll();
        CKFinder.setupCKEditor( editor );
    })

</script>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\PublicAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\Category;

PublicAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>

	<!-- Behavioral Meta Data -->
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link rel="icon" type="image/png" href="/public/img/small-logo-01.png">
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,900,900italic,700italic,700,500italic,400italic,500,300italic,300' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
	<link href='/public/<?= (isset($this->params['css'])) ? $this->params['css'] : 'style' ?>.css' rel='stylesheet' type='text/css'>
</head>
<body class="sticky_footer">
	<?php $this->beginBody() ?>

	<?= $this->render('/partials/header');?>
	<div id="wrapper-container">
		<?= $content ?>
	</div>
	<?= $this->render('/partials/footer');?>

	<!-- SCRIPT -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script type="text/javascript" src="/public/js/jquery.scrollTo.min.js"></script>
	<script type="text/javascript" src="/public/js/jquery.localScroll.min.js"></script>
	<script type="text/javascript" src="/public/js/jquery-animate-css-rotate-scale.js"></script>
	<script type="text/javascript" src="/public/js/fastclick.min.js"></script>
	<script type="text/javascript" src="/public/js/jquery.animate-colors-min.js"></script>
	<script type="text/javascript" src="/public/js/jquery.animate-shadow-min.js"></script>    
	<script type="text/javascript" src="/public/<?= (isset($this->params['js'])) ? $this->params['js'] : 'js/main' ?>.js"></script>
	<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>